[tool.poetry]
name = "pubmed-fetcher"
version = "0.1.0"
description = "A CLI tool to fetch research papers from PubMed"
authors = ["Your Name"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"

[tool.poetry.scripts]
get-papers-list = "pubmed_fetcher.cli:main"